version: "3.9"

services:
  bot:
    build: .
    container_name: flore_bot
    restart: always
    env_file:
      - .env
    command: python -m flore_bot.run_bot
    volumes:
      - .:/app
    depends_on: []

  api:
    build: .
    container_name: flore_api
    restart: always
    env_file:
      - .env
    command: uvicorn flore_bot.main:app --host 0.0.0.0 --port 8075 --reload
    ports:
      - "8075:8075"
    volumes:
      - .:/app
    depends_on: []
