FROM python:3.11-slim

RUN pip install poetry

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1

WORKDIR /app

COPY pyproject.toml poetry.lock ./
COPY flore_bot ./flore_bot
# COPY .env ./

RUN poetry install --no-root

EXPOSE 8075

CMD ["uvicorn", "flore_bot.main:app", "--host", "0.0.0.0", "--port", "8075"]
