services:
  - type: web
    name: flore-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: uvicorn flore_bot.main:app --host 0.0.0.0 --port 8075
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
      - key: URL_JS
      - key: CHAT_IDS

  - type: worker
    name: flore-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: python -m flore_bot.run_bot
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
      - key: URL_JS
      - key: CHAT_IDS
